# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export DENO_INSTALL="/c/Users/AsanoKunimitsu/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

source ~/.bashrc
